# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('mark', models.CharField(choices=[('AT', 'Attempt'), ('PR', 'Present'), ('LT', 'Late'), ('AB', 'Absent')], default='AT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='classId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Class'),
        ),
    ]
