# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 07:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendancePK', models.IntegerField(primary_key=True, serialize=False)),
                ('classId', models.IntegerField()),
                ('className', models.CharField(max_length=100)),
                ('studentFirstName', models.CharField(max_length=100)),
                ('studentLastName', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2016, 4, 23, 7, 54, 13, 702510, tzinfo=utc))),
                ('time', models.TimeField(default=datetime.datetime(2016, 4, 23, 7, 54, 13, 702577, tzinfo=utc))),
                ('mark', models.CharField(choices=[('Attempt', 'Attempt'), ('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], default='Attempt', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ClassPK', models.IntegerField(primary_key=True, serialize=False)),
                ('classId', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('startTime', models.TimeField(default=datetime.datetime(2016, 4, 23, 7, 54, 13, 699541, tzinfo=utc))),
                ('endTime', models.TimeField(default=datetime.datetime(2016, 4, 23, 7, 54, 13, 699576, tzinfo=utc))),
                ('startDate', models.DateField(default=datetime.datetime(2016, 4, 23, 7, 54, 13, 699601, tzinfo=utc))),
                ('endDate', models.DateField(default=datetime.datetime(2016, 4, 23, 7, 54, 13, 699647, tzinfo=utc))),
                ('lateThreshold', models.TimeField(blank=True, null=True)),
                ('absentThreshold', models.TimeField(blank=True, null=True)),
                ('locationFlag', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('codeFlag', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('codeExpirationDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRequest',
            fields=[
                ('classRequestPK', models.IntegerField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=100)),
                ('universityName', models.CharField(max_length=100)),
                ('userType', models.BooleanField(default=False)),
                ('classIdKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoster',
            fields=[
                ('classRosterPK', models.IntegerField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=100)),
                ('studentName', models.CharField(max_length=100)),
                ('professorName', models.CharField(max_length=100)),
                ('adminName', models.CharField(max_length=100)),
                ('classIdKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Class')),
                ('userIdKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityDim',
            fields=[
                ('UniversityDimPK', models.IntegerField(primary_key=True, serialize=False)),
                ('universityCode', models.IntegerField()),
                ('universityName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailDim',
            fields=[
                ('UserDetailDimPK', models.IntegerField(primary_key=True, serialize=False)),
                ('schoolId', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('universityCode', models.IntegerField()),
                ('universityKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UniversityDim')),
                ('userIdKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classrequest',
            name='schoolIdKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserDetailDim'),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='userIdKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='universityKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UniversityDim'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='classkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Class'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='userIdKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
