# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.CharField(choices=[('Attempt', 'Attempt'), ('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], default='Attempt', max_length=10),
        ),
    ]
