# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 26, 8, 43, 44, 911448, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
