# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='ClassPK',
            new_name='classPK',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='UniversityPK',
            new_name='universityPK',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='UserDetailDimPK',
            new_name='userDetailPK',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 4, 23, 9, 51, 12, 434170, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 4, 23, 9, 51, 12, 434214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='class',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2016, 4, 23, 9, 51, 12, 432830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='class',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2016, 4, 23, 9, 51, 12, 432713, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='class',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2016, 4, 23, 9, 51, 12, 432740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='class',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2016, 4, 23, 9, 51, 12, 432670, tzinfo=utc)),
        ),
    ]
