# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 09:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_class_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 4, 26, 9, 41, 2, 403710, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(auto_now=True, default=datetime.datetime(2016, 4, 26, 9, 41, 12, 603670, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.CharField(choices=[('attempt', 'attempt'), ('present', 'present'), ('late', 'late'), ('absent', 'absent')], default='attempt', max_length=10),
        ),
    ]
