# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160423_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrequest',
            old_name='userType',
            new_name='requestType',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='userType',
            field=models.CharField(default='student', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
