# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20160419_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='codeExpirationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='codeFlag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='locationFlag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
