# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20160421_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='absentThreshold',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='lateThreshold',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
